### ISSUE TITLE
Problem with count() in PHP 7.2

### ISSUE THREAD

**Issue by Ilya-Zhulin** [JBZoo/JBDump#3]
In order with [http://php.net/manual/en/function.count.php#refsect1-function.count-changelog](url) count function works only with countable objects. JBDump has problem with each object, because it tries to count object's properties.

**Comment by SmetDenis** [comment]
Hi 

Can you add pull request to fix it?

Thanks.

**Comment by Ilya-Zhulin** [comment]
))) I'll try.... But I don't know now, what can we do.

**Comment by Ilya-Zhulin** [comment]
I've done it. Maybe, it's stupid method, but it works...

**Comment by SmetDenis** [comment]
Merged.
Thnx
